# https://learn.microsoft.com/en-us/azure/openshift/howto-multiple-ips
- name: scale_outboundips | Increase outbound IPs by one
  when: |
    outbound_type | d("Loadbalancer") != "UserDefinedRouting"
    and lb_ip_count | d("1") | int < 20
  block:
    - name: scale_outboundips | Update cluster with oubound IPs + 1
      ansible.builtin.command:
        argv: "{{ argv | reject('equalto', omit) | list }}"
      vars:
        argv:
          - az
          - aro
          - update
          - --name={{ cluster_name }}
          - --resource-group={{ resource_group }}
          - --load-balancer-managed-outbound-ip-count={{ (lb_ip_count | d("1") | int) + 1 }}
          - -o=yaml
      delegate_to: localhost
      register: smoketest_aro_update_scaleupips
      changed_when: smoketest_aro_update_scaleupips.rc == 0
    - name: scale_outboundips | Debug smoketest_aro_update_scaleupips
      ansible.builtin.debug:
        var: smoketest_aro_update_scaleupips
        verbosity: 1
    - name: scale_outboundips | Update cluster with oubound IPs - 1
      ansible.builtin.command:
        argv: "{{ argv | reject('equalto', omit) | list }}"
      vars:
        argv:
          - az
          - aro
          - update
          - --name={{ cluster_name }}
          - --resource-group={{ resource_group }}
          - --load-balancer-managed-outbound-ip-count={{ (lb_ip_count | d("1") | int) }}
          - -o=yaml
      delegate_to: localhost
      register: smoketest_aro_update_scaledownips
      changed_when: smoketest_aro_update_scaledownips.rc == 0
    - name: scale_outboundips | Debug smoketest_aro_update_scaledownips
      ansible.builtin.debug:
        var: smoketest_aro_update_scaledownips
        verbosity: 1
